[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown2>=2.5.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
]
